sudo: false
dist: trusty
language: ruby
cache:
  bundler: true
rvm:
  - ruby-head
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - jruby-9.2.7.0
  - rbx-3
gemfile:
  - test/gemfiles/Gemfile.rails-6.0.x
  - test/gemfiles/Gemfile.rails-5.2.x
  - test/gemfiles/Gemfile.rails-5.1.x
  - test/gemfiles/Gemfile.rails-5.0.x
  - test/gemfiles/Gemfile.rails-5.0.x.erubi
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.0.x
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.2.10
      gemfile: test/gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.3.8
      gemfile: test/gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.4.9
      gemfile: test/gemfiles/Gemfile.rails-6.0.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.2.10
      gemfile: test/gemfiles/Gemfile.rails-5.2.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x.erubi
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.0.x.erubi
    - rvm: 2.4.9
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.4.9
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.4.9
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5.7
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.5.7
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.5.7
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.6.5
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.6.5
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.6.5
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.7.0
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.7.0
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.7.0
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
    - rvm: ruby-head
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: ruby-head
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: ruby-head
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
  include:
    - rvm: 2.6.5
      gemfile: test/gemfiles/Gemfile.rails-edge
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - gemfile: test/gemfiles/Gemfile.rails-edge
    - rvm: jruby-9.2.7.0
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
    - rvm: jruby-9.2.7.0
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: jruby-9.2.7.0
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: jruby-9.2.7.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x.erubi
  fast_finish: true
before_install:
  # install older versions of rubygems and bundler only on Ruby < 2.7
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem i rubygems-update -v '<3' && update_rubygems; fi; # https://github.com/travis-ci/travis-ci/issues/8974
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true; fi;
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem i bundler -v '<2'; fi;
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: "bundle exec rake submodules test"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT